# Generated by Django 2.0.6 on 2018-06-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_uwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uwords',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
