# Generated by Django 2.0.6 on 2018-06-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_uwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
